image: node:16.17.1

stages:
  - setup
  - test
  - deploy

install:
  stage: setup
  script: 
    - npm ci --force

unit test:
  stage: test
  before_script:
    - apt-get update
    - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    - apt install -y ./google-chrome*.deb;
    - export CHROME_BIN=/usr/bin/google-chrome
  script:
    - npm ci --force
    - npm run test -- --no-watch --browsers=ChromeHeadlessCI

deploy:
  stage: deploy
  script:
    - echo "Deploy teste"
  only:
    - master